title: セキュリティの終わりのない道

description: > # this means to ignore newlines until "baseurl:"
  セキュリティに関する学びや情報を本ブログで発信します。
permalink: ':title/'
#baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Usek2g # add your name
author-img: daruma.jpeg # add your photo
about-author: 昭和生まれのエンジニアです。今はベンチャー気質の会社でセキュリティエンジニアを担当しています。趣味はゴルフと銭湯。おっさんか？ # add description
social-twitter: Usek2g # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github:  Usek2g # add your Github handle
#social-linkedin: # add your Linkedin handle
social-email: Usek.2g@gmail.com # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
